version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: pavanvarikolu  # corrected
      MONGO_INITDB_ROOT_PASSWORD: pavankalyan    # corrected
      MONGO_INITDB_DATABASE: prescripto          # add database initialization
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - prescripto

  backend:
    image: pavanvarikolu/prescriptobackendapp:1.0
    container_name: backend
    command: npm run server                      # corrected
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://pavanvarikolu:pavankalyan@34.194.48.167:27017/prescripto  # corrected URI
    networks:
      - prescripto

  frontend:
    image: pavanvarikolu/prescriptofrontendapp:1.0
    container_name: frontend-container
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - prescripto


networks:
  prescripto:
    driver: bridge

volumes:
  mongo-data:
