apiVersion: v1
kind: Secret
metadata:
  namespace: prescripto-app
  name: mongo-creds
type: Opaque
data:
  username: cGF2YW52YXJpa29sdQ== # Base64 encoded "pavanvarikolu"
  password: cGF2YW5rYWx5YW4= # Base64 encoded "pavankalyan"
