apiVersion: v1
kind: Service
metadata:
  namespace: prescripto-app
  name: mongodb-service
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32000
  selector:
    app: mongodb
