apiVersion: v1
kind: Service
metadata:
  namespace: prescripto-app
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017 # Port exposed by the service
      targetPort: 27017 # Port on the MongoDB container
  type: ClusterIP # Default service type for internal communication
