apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: prescripto-app
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard # Ensure this matches your cluster's storage class
