apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prescripto-app
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest # Make sure to replace with your actual image
          ports:
            - containerPort: 3000
      dependsOn:
        - name: backend
          condition: ServiceAvailable
